version: 2

references:
  dependencies_key: &dependencies_key
    sbt-v2-deps-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}

  restore_dependencies: &restore_dependencies
    restore_cache:
      keys:
        - *dependencies_key

  sbt_image: &sbt_image
    moia/scala-on-circleci:8u222-2.12.10-sbt-1.3.3

  sbtCommand: &sbtCommand

jobs:
  test:
    docker:
      - image: *sbt_image
    steps:
      - checkout
      - *restore_dependencies
      - run:
         name: Compile and Test
         command: |
           sbt -J-Xms512m -J-Xmx2g -no-colors -batch "; +test; +doc; version"
      - save_cache:
          key: *dependencies_key
          paths:
            - ~/.m2
            - ~/.ivy2
            - ~/.sbt
            - ~/.cache/coursier/

  publishRelease:
    docker:
      - image: *sbt_image
    steps:
      - checkout
      - *restore_dependencies
      - run:
          name: Publish
          command: |
            sbt -J-Xms512m -J-Xmx2g -no-colors -batch "; version; +publish"
      - save_cache:
          key: *dependencies_key
          paths:
            - ~/.m2
            - ~/.ivy2
            - ~/.sbt
            - ~/.cache/coursier/

workflows:
  version: 2
  testDevelopmentBranch:
    jobs:
      - test:
          context: sbt-release-ci-library
          filters:
            branches:
              ignore:
                - master
            tags:
              ignore: /.*/

  publishRelease:
    jobs:
      - publishRelease:
          context: sbt-release-ci-library
          filters:
            branches:
              only:
                - master
                - init
